# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_projet', models.CharField(help_text='Code unique (ex: JAMM-LEYDI-2024)', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bailleurs', models.TextField(help_text='Liste des bailleurs (ex: Union Européenne, AFD...)')),
                ('zone_intervention', models.TextField(help_text="Description de la zone d'intervention")),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget total en FCFA ou EUR', max_digits=15, null=True)),
                ('devise', models.CharField(default='EUR', help_text='EUR, FCFA, USD...', max_length=3)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu'), ('PLANIFIE', 'Planifié')], default='EN_COURS', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projets/logos/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('organisation', models.CharField(blank=True, help_text="Organisation d'appartenance (GRDR, partenaire, etc.)", max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN_PROJET', 'Administrateur du projet'), ('CONTRIBUTEUR', 'Contributeur (saisie des données)'), ('LECTEUR', 'Lecteur (consultation uniquement)')], max_length=20)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True, help_text="Permet de désactiver l'accès sans supprimer")),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_users', to='core.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur-Projet',
                'verbose_name_plural': 'Utilisateurs-Projets',
                'ordering': ['projet', 'user'],
                'unique_together': {('user', 'projet')},
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='users',
            field=models.ManyToManyField(related_name='projets', through='core.UserProjet', to=settings.AUTH_USER_MODEL),
        ),
    ]
