# Generated by Django 5.2.7 on 2025-11-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='equipe_grdr',
            field=models.CharField(blank=True, help_text='Équipe GRDR de rattachement (ex: Antenne Sénégal, Siège Paris...)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='pays',
            field=models.CharField(default='Sénégal', help_text="Pays d'intervention", max_length=100),
        ),
    ]
