# Generated by Django 5.2.7 on 2025-11-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_step3_cleanup'),
        ('geo', '0003_admin2_cellulesgrdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='pays',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Pays d'intervention (niveau Admin2)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='geo.admin2'),
        ),
    ]
