# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_commune', models.CharField(help_text='Code officiel de la commune', max_length=20, unique=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, help_text='Population recensée', null=True)),
                ('annee_recensement', models.IntegerField(blank=True, help_text='Année du dernier recensement', null=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone_poi', models.CharField(default='users', help_text="Nom de l'icône FontAwesome", max_length=50)),
                ('couleur_hex', models.CharField(default='#FFC107', help_text='Couleur du marqueur', max_length=7)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'acteur",
                'verbose_name_plural': "Types d'acteurs",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone_poi', models.CharField(default='map-marker', help_text="Nom de l'icône FontAwesome ou chemin fichier", max_length=50)),
                ('couleur_hex', models.CharField(default='#28A745', help_text='Couleur du marqueur sur la carte', max_length=7)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'infrastructure",
                'verbose_name_plural': "Types d'infrastructures",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Code court (ex: ASP, ECO, HYD...)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur_hex', models.CharField(default='#0066CC', help_text='Couleur pour les graphiques (ex: #FF5733)', max_length=7)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'intervention",
                'verbose_name_plural': "Types d'interventions",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ChefLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du chef-lieu (peut différer de la commune)', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('commune', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_lieu', to='referentiels.commune')),
            ],
            options={
                'verbose_name': 'Chef-lieu',
                'verbose_name_plural': 'Chefs-lieux',
            },
        ),
        migrations.CreateModel(
            name='CommuneGeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Contour administratif de la commune', srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroïde calculé automatiquement', null=True, srid=4326)),
                ('superficie', models.FloatField(blank=True, help_text='Superficie en km²', null=True)),
                ('commune', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometrie', to='referentiels.commune')),
            ],
            options={
                'verbose_name': 'Géométrie de commune',
                'verbose_name_plural': 'Géométries des communes',
            },
        ),
        migrations.CreateModel(
            name='ProjetCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('prioritaire', models.BooleanField(default=False, help_text='Commune prioritaire pour ce projet')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune_projets', to='referentiels.commune')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_communes', to='core.projet')),
            ],
            options={
                'verbose_name': 'Projet-Commune',
                'verbose_name_plural': 'Projets-Communes',
                'ordering': ['projet', 'commune'],
                'unique_together': {('projet', 'commune')},
            },
        ),
    ]
