# Generated by Django 5.2.7 on 2025-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeGRDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Antenne Sénégal - Kédougou', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Code court (ex: SN-KED, FR-PARIS)', max_length=50, unique=True)),
                ('type_equipe', models.CharField(choices=[('SIEGE', 'Siège'), ('ANTENNE', 'Antenne'), ('BUREAU', 'Bureau'), ('COORDINATION', 'Coordination')], default='ANTENNE', max_length=20)),
                ('pays', models.CharField(help_text="Pays d'implantation", max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, help_text="Nom du responsable de l'équipe", max_length=200, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Équipe GRDR',
                'verbose_name_plural': 'Équipes GRDR',
                'ordering': ['type_equipe', 'pays', 'nom'],
            },
        ),
    ]
