# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInsecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gravite_defaut', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], default='MOYENNE', help_text='Niveau de gravité par défaut', max_length=10)),
                ('couleur_hex', models.CharField(default='#DC3545', help_text='Couleur pour les cartes et graphiques', max_length=7)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'insécurité",
                'verbose_name_plural': "Types d'insécurité",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Titre court de l'incident", max_length=255)),
                ('description', models.TextField(help_text="Description détaillée de l'incident")),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('nb_personnes_affectees', models.IntegerField(blank=True, help_text='Nombre de personnes affectées', null=True)),
                ('impact_economique', models.TextField(blank=True, help_text="Description de l'impact économique", null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Localisation de l'incident", null=True, srid=4326)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_dit', models.CharField(blank=True, help_text='Lieu-dit ou localisation descriptive', max_length=200, null=True)),
                ('date_incident', models.DateField(help_text="Date de l'incident")),
                ('heure_incident', models.TimeField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('parties_impliquees', models.TextField(blank=True, help_text='Acteurs/communautés impliqués', null=True)),
                ('temoins', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('SIGNALE', 'Signalé'), ('EN_VERIFICATION', 'En vérification'), ('CONFIRME', 'Confirmé'), ('RESOLU', 'Résolu'), ('CLOS', 'Clos'), ('FAUSSE_ALERTE', 'Fausse alerte')], default='SIGNALE', max_length=20)),
                ('actions_entreprises', models.TextField(blank=True, help_text='Actions de médiation/résolution', null=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('resolution_description', models.TextField(blank=True, null=True)),
                ('source_signalement', models.CharField(choices=[('TERRAIN', 'Équipe terrain'), ('COMMUNAUTE', 'Communauté locale'), ('AUTORITE', 'Autorités'), ('PARTENAIRE', 'Partenaire'), ('KOBO', 'Formulaire Kobo'), ('AUTRE', 'Autre')], default='TERRAIN', max_length=20)),
                ('contact_signalant', models.CharField(blank=True, help_text='Nom/contact de la personne ayant signalé', max_length=100, null=True)),
                ('confidentiel', models.BooleanField(default=False, help_text='Marquer comme confidentiel (non publié)')),
                ('notes_confidentielles', models.TextField(blank=True, help_text='Notes internes confidentielles', null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='referentiels.commune')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reports_crees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reports_modifies', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='core.projet')),
                ('type_insecurite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='securite.typeinsecurite')),
            ],
            options={
                'verbose_name': 'Rapport de sécurité',
                'verbose_name_plural': 'Rapports de sécurité',
                'ordering': ['-date_incident', '-date_signalement'],
                'indexes': [models.Index(fields=['projet', 'commune', 'date_incident'], name='securite_se_projet__19d989_idx'), models.Index(fields=['type_insecurite', 'statut'], name='securite_se_type_in_059b9e_idx'), models.Index(fields=['gravite'], name='securite_se_gravite_d39ea7_idx')],
            },
        ),
    ]
