# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'infrastructure (ex: Forage de Gathiary)", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text="Localisation GPS de l'infrastructure", srid=4326)),
                ('adresse', models.CharField(blank=True, help_text='Adresse ou localisation descriptive', max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_beneficiaires', models.IntegerField(blank=True, help_text='Nombre de bénéficiaires directs', null=True)),
                ('nb_beneficiaires_indirects', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_CONSTRUCTION', 'En construction'), ('FONCTIONNEL', 'Fonctionnel'), ('EN_PANNE', 'En panne'), ('ABANDONNE', 'Abandonné')], default='PLANIFIE', max_length=20)),
                ('date_construction', models.DateField(blank=True, null=True)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('caracteristiques', models.JSONField(blank=True, default=dict, help_text='Caractéristiques spécifiques (débit, capacité, etc.)')),
                ('cout_construction', models.DecimalField(blank=True, decimal_places=2, help_text='Coût en devise du projet', max_digits=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='infrastructures/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'ordering': ['commune', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(help_text="Nom de l'organisation", max_length=255)),
                ('sigle', models.CharField(blank=True, help_text='Sigle ou acronyme', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text="Localisation du siège/local de l'organisation", srid=4326)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_adherents', models.IntegerField(blank=True, help_text='Nombre de membres/adhérents', null=True)),
                ('nb_femmes', models.IntegerField(blank=True, help_text='Nombre de femmes membres', null=True)),
                ('nb_hommes', models.IntegerField(blank=True, help_text="Nombre d'hommes membres", null=True)),
                ('nb_jeunes', models.IntegerField(blank=True, help_text='Nombre de jeunes (< 35 ans)', null=True)),
                ('responsable', models.CharField(blank=True, help_text='Nom du responsable/président', max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_CREATION', 'En création')], default='ACTIF', max_length=20)),
                ('date_creation_org', models.DateField(blank=True, help_text="Date de création de l'organisation", null=True)),
                ('date_reconnaissance', models.DateField(blank=True, help_text='Date de reconnaissance officielle', null=True)),
                ('domaines_activite', models.JSONField(blank=True, default=list, help_text="Liste des domaines d'activité")),
                ('photo', models.ImageField(blank=True, help_text='Photo du groupe ou du local', null=True, upload_to='acteurs/')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acteurs', to='referentiels.commune')),
            ],
            options={
                'verbose_name': 'Acteur',
                'verbose_name_plural': 'Acteurs',
                'ordering': ['commune', 'denomination'],
            },
        ),
    ]
