# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('geo', '0001_initial'),
        ('referentiels', '0001_initial'),
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='interventions',
            field=models.ManyToManyField(related_name='acteurs_impliques', through='suivi.InterventionActeur', to='suivi.intervention'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acteurs', to='core.projet'),
        ),
        migrations.AddField(
            model_name='acteur',
            name='type_acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acteurs', to='referentiels.typeacteur'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='referentiels.commune'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='interventions',
            field=models.ManyToManyField(related_name='infrastructures_liees', through='suivi.InterventionInfrastructure', to='suivi.intervention'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='core.projet'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='type_infrastructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructures', to='referentiels.typeinfrastructure'),
        ),
        migrations.AddIndex(
            model_name='acteur',
            index=models.Index(fields=['projet', 'commune'], name='geo_acteur_projet__0e7a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='acteur',
            index=models.Index(fields=['type_acteur'], name='geo_acteur_type_ac_1443a4_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['projet', 'commune'], name='geo_infrast_projet__8178d5_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['type_infrastructure'], name='geo_infrast_type_in_2b5002_idx'),
        ),
    ]
