# Generated by Django 5.2.7 on 2025-11-25 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=254, null=True)),
                ('osm_way_id', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Nom du pays', max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('aeroway', models.CharField(blank=True, max_length=254, null=True)),
                ('amenity', models.CharField(blank=True, max_length=254, null=True)),
                ('admin_leve', models.CharField(blank=True, db_column='admin_leve', help_text='Niveau administratif', max_length=254, null=True)),
                ('barrier', models.CharField(blank=True, max_length=254, null=True)),
                ('boundary', models.CharField(blank=True, max_length=254, null=True)),
                ('building', models.CharField(blank=True, max_length=254, null=True)),
                ('craft', models.CharField(blank=True, max_length=254, null=True)),
                ('geological', models.CharField(blank=True, max_length=254, null=True)),
                ('historic', models.CharField(blank=True, max_length=254, null=True)),
                ('land_area', models.CharField(blank=True, max_length=254, null=True)),
                ('landuse', models.CharField(blank=True, max_length=254, null=True)),
                ('leisure', models.CharField(blank=True, max_length=254, null=True)),
                ('man_made', models.CharField(blank=True, max_length=254, null=True)),
                ('military', models.CharField(blank=True, max_length=254, null=True)),
                ('natural', models.CharField(blank=True, max_length=254, null=True)),
                ('office', models.CharField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
                ('shop', models.CharField(blank=True, max_length=254, null=True)),
                ('sport', models.CharField(blank=True, max_length=254, null=True)),
                ('tourism', models.CharField(blank=True, max_length=254, null=True)),
                ('other_tags', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Pays (Admin2)',
                'verbose_name_plural': 'Pays (Admin2)',
                'db_table': 'geo."admin-2"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellulesGRDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom officiel de la cellule', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordonnées géographiques de la cellule (SRID 4326)', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Cellule GRDR',
                'verbose_name_plural': 'Cellules GRDR',
                'db_table': 'geo.cellules_grdr',
                'managed': False,
            },
        ),
    ]
