# Generated by Django 5.2.7 on 2025-11-25 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_admin2_cellulesgrdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=254, null=True)),
                ('osm_way_id', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Nom de la région', max_length=254, null=True)),
                ('admin_leve', models.CharField(blank=True, max_length=254, null=True)),
                ('boundary', models.CharField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Région (Admin4)',
                'verbose_name_plural': 'Régions (Admin4)',
                'db_table': '"geo"."admin-4"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=254, null=True)),
                ('osm_way_id', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Nom du département', max_length=254, null=True)),
                ('admin_leve', models.CharField(blank=True, max_length=254, null=True)),
                ('boundary', models.CharField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Département (Admin5)',
                'verbose_name_plural': 'Départements (Admin5)',
                'db_table': '"geo"."admin-5"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=254, null=True)),
                ('osm_way_id', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text="Nom de l'arrondissement", max_length=254, null=True)),
                ('admin_leve', models.CharField(blank=True, max_length=254, null=True)),
                ('boundary', models.CharField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Arrondissement (Admin7)',
                'verbose_name_plural': 'Arrondissements (Admin7)',
                'db_table': '"geo"."admin-7"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=254, null=True)),
                ('osm_way_id', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, help_text='Nom de la commune', max_length=254, null=True)),
                ('admin_leve', models.CharField(blank=True, max_length=254, null=True)),
                ('boundary', models.CharField(blank=True, max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Commune (Admin8)',
                'verbose_name_plural': 'Communes (Admin8)',
                'db_table': '"geo"."admin-8"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='admin2',
            table='"geo"."admin-2"',
        ),
        migrations.AlterModelTable(
            name='cellulesgrdr',
            table='"geo"."cellules-grdr"',
        ),
    ]
