# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('geo', '0001_initial'),
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique de l'indicateur (ex: R1.1, R2.3...)", max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unite_mesure', models.CharField(default='Nombre', help_text='Ex: Nombre, Personnes, Hectares, %, etc.', max_length=50)),
                ('type_calcul', models.CharField(choices=[('SOMME', 'Somme des valeurs'), ('MOYENNE', 'Moyenne des valeurs'), ('DENOMBREMENT', 'Comptage des occurrences'), ('MANUEL', 'Saisie manuelle uniquement')], default='SOMME', help_text='Mode de calcul pour agréger les valeurs', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'ordering': ['thematique', 'ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('ACTIVITE', 'Activité (formation, réunion, sensibilisation...)'), ('REALISATION', 'Réalisation (infrastructure, équipement...)')], default='ACTIVITE', help_text='Activité (immatériel) ou Réalisation (matériel)', max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('valeur_quantitative', models.DecimalField(blank=True, decimal_places=2, help_text='Nb participants, bénéficiaires, quantité produite...', max_digits=10, null=True)),
                ('date_intervention', models.DateField(help_text="Date de l'intervention")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Localisation précise de l'intervention", null=True, srid=4326)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_REVISION', 'En révision'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=20)),
                ('notes_revision', models.TextField(blank=True, help_text='Commentaires pour corrections', null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='interventions/')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='referentiels.commune')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_creees', to=settings.AUTH_USER_MODEL)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='suivi.indicateur')),
                ('type_intervention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='referentiels.typeintervention')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='InterventionActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="Rôle de l'acteur dans l'intervention", max_length=100, null=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.acteur')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.intervention')),
            ],
            options={
                'verbose_name': 'Intervention-Acteur',
                'verbose_name_plural': 'Interventions-Acteurs',
            },
        ),
        migrations.CreateModel(
            name='InterventionInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.infrastructure')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.intervention')),
            ],
            options={
                'verbose_name': 'Intervention-Infrastructure',
                'verbose_name_plural': 'Interventions-Infrastructures',
            },
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code court (ex: R1, R2, R3...)', max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, help_text='Pour trier les thématiques dans les dashboards')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematiques', to='core.projet')),
            ],
            options={
                'verbose_name': 'Thématique',
                'verbose_name_plural': 'Thématiques',
                'ordering': ['projet', 'ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='indicateur',
            name='thematique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='suivi.thematique'),
        ),
        migrations.CreateModel(
            name='ValeurIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_realisee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_mesure', models.DateField(help_text='Date de la mesure/saisie')),
                ('source', models.CharField(choices=[('SAISIE_MANUELLE', 'Saisie manuelle'), ('CALCUL_AUTO', 'Calcul automatique'), ('IMPORT_EXTERNE', 'Import externe (Excel, Kobo...)')], default='SAISIE_MANUELLE', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(default=django.utils.timezone.now)),
                ('commune', models.ForeignKey(blank=True, help_text='Laisser vide pour valeur globale projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentiels.commune')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='suivi.indicateur')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valeurs_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Valeur d'indicateur",
                'verbose_name_plural': 'Valeurs des indicateurs',
                'ordering': ['-date_mesure'],
            },
        ),
        migrations.CreateModel(
            name='CibleIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_cible', models.DecimalField(decimal_places=2, help_text='Valeur à atteindre', max_digits=12)),
                ('annee', models.IntegerField(help_text='Année de la cible (ex: 2025, 2026)')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('commune', models.ForeignKey(blank=True, help_text='Laisser vide pour une cible globale projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentiels.commune')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='suivi.indicateur')),
            ],
            options={
                'verbose_name': "Cible d'indicateur",
                'verbose_name_plural': 'Cibles des indicateurs',
                'ordering': ['indicateur', 'annee', 'commune'],
                'unique_together': {('indicateur', 'commune', 'annee')},
            },
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['indicateur', 'commune', 'date_intervention'], name='suivi_inter_indicat_0d8457_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['statut'], name='suivi_inter_statut_58289c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interventionacteur',
            unique_together={('intervention', 'acteur')},
        ),
        migrations.AlterUniqueTogether(
            name='interventioninfrastructure',
            unique_together={('intervention', 'infrastructure')},
        ),
        migrations.AlterUniqueTogether(
            name='thematique',
            unique_together={('projet', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='indicateur',
            unique_together={('thematique', 'code')},
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['indicateur', 'date_mesure'], name='suivi_valeu_indicat_349713_idx'),
        ),
        migrations.AddIndex(
            model_name='valeurindicateur',
            index=models.Index(fields=['commune', 'date_mesure'], name='suivi_valeu_commune_d79ee3_idx'),
        ),
    ]
