# Generated by Django 5.2.7 on 2025-11-10 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_projet_fields(apps, schema_editor):
    """
    Remplir les champs projet à partir des relations existantes
    - Pour Indicateur : via thematique.projet
    - Pour Intervention : via indicateur.thematique.projet
    """
    Indicateur = apps.get_model('suivi', 'Indicateur')
    Intervention = apps.get_model('suivi', 'Intervention')

    # Remplir les projets pour les indicateurs
    print("\n  Mise à jour des indicateurs...")
    indicateurs = Indicateur.objects.select_related('thematique').all()
    count_ind = 0
    for indicateur in indicateurs:
        indicateur.projet = indicateur.thematique.projet
        indicateur.save(update_fields=['projet'])
        count_ind += 1
    print(f"  -> {count_ind} indicateur(s) mis à jour")

    # Remplir les projets pour les interventions
    print("\n  Mise à jour des interventions...")
    interventions = Intervention.objects.select_related('indicateur__thematique').all()
    count_int = 0
    for intervention in interventions:
        intervention.projet = intervention.indicateur.thematique.projet
        intervention.save(update_fields=['projet'])
        count_int += 1
    print(f"  -> {count_int} intervention(s) mise(s) à jour\n")


def reverse_populate(apps, schema_editor):
    """Fonction vide pour le rollback"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_pays_equipe_to_projet'),
        ('referentiels', '0001_initial'),
        ('suivi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicateur',
            options={'ordering': ['projet', 'thematique__ordre', 'ordre', 'code'], 'verbose_name': 'Indicateur', 'verbose_name_plural': 'Indicateurs'},
        ),
        migrations.RemoveIndex(
            model_name='intervention',
            name='suivi_inter_indicat_0d8457_idx',
        ),
        migrations.AlterUniqueTogether(
            name='indicateur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='projet',
            field=models.ForeignKey(blank=True, help_text='Projet auquel appartient cet indicateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='core.projet'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='projet',
            field=models.ForeignKey(blank=True, help_text='Projet auquel appartient cette intervention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.projet'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='thematique',
            field=models.ForeignKey(help_text='Thématique du projet', on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='suivi.thematique'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='indicateur',
            field=models.ForeignKey(help_text='Indicateur du projet', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='suivi.indicateur'),
        ),
        # Remplir les champs projet avant d'ajouter les contraintes
        migrations.RunPython(populate_projet_fields, reverse_populate),
        migrations.AlterUniqueTogether(
            name='indicateur',
            unique_together={('projet', 'code')},
        ),
        migrations.AddIndex(
            model_name='indicateur',
            index=models.Index(fields=['projet', 'thematique'], name='suivi_indic_projet__72547e_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['projet', 'indicateur', 'commune', 'date_intervention'], name='suivi_inter_projet__090315_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['projet', 'statut'], name='suivi_inter_projet__22a040_idx'),
        ),
    ]
