# Generated by Django 5.2.7 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_alter_indicateur_projet_alter_intervention_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cibleindicateur',
            name='valeur_cible',
            field=models.IntegerField(help_text='Valeur à atteindre'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='valeur_quantitative',
            field=models.IntegerField(blank=True, help_text='Nb participants, bénéficiaires, quantité produite...', null=True),
        ),
        migrations.AlterField(
            model_name='valeurindicateur',
            name='valeur_realisee',
            field=models.IntegerField(help_text='Valeur réalisée (nombre entier)'),
        ),
    ]
