# Generated by Django 5.2.7 on 2025-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0004_alter_cibleindicateur_valeur_cible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='notes_revision',
        ),
        migrations.AddField(
            model_name='intervention',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes ou commentaires', null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('PROGRAMME', 'Programmé'), ('TERMINE', 'Terminé'), ('ANNULEE', 'Annulée')], default='PROGRAMME', max_length=20),
        ),
    ]
